name: Build and Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            suffix: ""
          - goos: linux
            goarch: arm64
            suffix: ""
          - goos: darwin
            goarch: amd64
            suffix: ""
          - goos: darwin
            goarch: arm64
            suffix: ""
          - goos: windows
            goarch: amd64
            suffix: ".exe"
          - goos: windows
            goarch: arm64
            suffix: ".exe"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        echo "Building for ${{ matrix.goos }}/${{ matrix.goarch }}"
        mkdir -p dist
        go build -v -ldflags="-s -w" -o dist/capture-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.suffix }} .
        echo "Build completed successfully"
        ls -la dist/

    - name: Create archive
      run: |
        cd dist
        if [ "${{ matrix.goos }}" = "windows" ]; then
          zip capture-${{ matrix.goos }}-${{ matrix.goarch }}.zip capture-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.suffix }}
        else
          tar -czf capture-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz capture-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.suffix }}
        fi

    - name: Generate checksum
      run: |
        cd dist
        if [ "${{ matrix.goos }}" = "windows" ]; then
          sha256sum capture-${{ matrix.goos }}-${{ matrix.goarch }}.zip > capture-${{ matrix.goos }}-${{ matrix.goarch }}.zip.sha256
        else
          sha256sum capture-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz > capture-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz.sha256
        fi

    - name: Upload Release Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd dist
        if [ "${{ matrix.goos }}" = "windows" ]; then
          gh release upload ${{ github.event.release.tag_name }} capture-${{ matrix.goos }}-${{ matrix.goarch }}.zip
          gh release upload ${{ github.event.release.tag_name }} capture-${{ matrix.goos }}-${{ matrix.goarch }}.zip.sha256
        else
          gh release upload ${{ github.event.release.tag_name }} capture-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
          gh release upload ${{ github.event.release.tag_name }} capture-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz.sha256
        fi